services:
  server:
    build: .
    ports:
      - 3001:3001
    depends_on:
      - database

  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - database:/var/lib/mongodb/data
    
volumes:
  database:
