services:
  server:
    build: .
    ports:
      - 3001:3001
    depends_on:
      - database
    restart: always
    environment:
      - MONGO_CONNECTION_URI=mongodb://database:27017/ecommerce
      - PORT=3001
      - TOKEN_SECRET=auhsd9a7d7221k9k1s901ks9wks9assamara

  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - database:/var/lib/mongodb/data
    
volumes:
  database:
